"""add_cancellation_to_crawl_jobs

Revision ID: 822401c8462f
Revises: 92c8cd7d4874
Create Date: 2026-02-08 19:38:04.060618+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822401c8462f'
down_revision: Union[str, None] = '92c8cd7d4874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_jobs', sa.Column('cancellation_requested', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('crawl_jobs', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_jobs', 'cancelled_at')
    op.drop_column('crawl_jobs', 'cancellation_requested')
    # ### end Alembic commands ###
